export enum EOpportunityType {
  INVESTMENT_OPPORTUNITY = 'INVESTMENT_OPPORTUNITY',
  ADVISORY = 'ADVISORY',
  INSURANCE = 'INSURANCE',
  FINANCIAL_SOLUTIONS ='FINANCIAL_SOLUTIONS',
  OTHER = 'OTHER'
}
